"""add operations table

Revision ID: c9dbbec31510
Revises: f34e64198b15
Create Date: 2025-03-27 10:52:49.741983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9dbbec31510'
down_revision = 'f34e64198b15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 